[mypy]
# plugins = mypy.plugins.proper_plugin, hydpy/mypy_plugin.py
check_untyped_defs = True
disallow_any_generics = True
enable_error_code =
    ignore-without-code,
    name-defined,
    redundant-expr,
    redundant-self,
    truthy-bool,
    truthy-iterable,
    unused-awaitable
exclude = HydPy-H-Lahn
extra_checks = True
ignore_missing_imports = True
no_implicit_reexport = True
warn_redundant_casts = True
warn_unreachable = True
warn_unused_ignores = True

[hydpy.mypy_plugin]
relevant_sources = hydpy

[mypy-hydpy.docs.auto.*]
ignore_errors = True

[mypy-hydpy.tests.plugin.*]
ignore_errors = True
[mypy-hydpy.models.meteo.*]
ignore_errors = True
[mypy-hydpy.models.manager.*]
ignore_errors = True
[mypy-hydpy.models.arma.*]
ignore_errors = True
[mypy-hydpy.models.exch.*]
ignore_errors = True
[mypy-hydpy.models.conv.*]
ignore_errors = True
[mypy-hydpy.models.lland.*]
ignore_errors = True
[mypy-hydpy.models.whmod.*]
ignore_errors = True
[mypy-hydpy.models.wland.*]
ignore_errors = True
[mypy-hydpy.models.wq.*]
ignore_errors = True
[mypy-hydpy.models.manager_lwc]
ignore_errors = True
[mypy-hydpy.core.*]
ignore_errors = True

[mypy-hydpy.interfaces.*]
disable_error_code = empty-body

[mypy-hydpy.models.*]
disable_error_code = type-abstract

[mypy-hydpy.tests.iotesting.*]
ignore_errors = True
