# pylint: disable=missing-docstring, unused-argument

from hydpy.core.typingtools import *

class BaseInterface:
    def reset_reuseflags(self) -> None: ...
    def load_data(self, idx: int) -> None: ...
    def save_data(self, idx: int) -> None: ...
    def update_inlets(self) -> None: ...
    def update_observers(self) -> None: ...
    def update_receivers(self, idx: int) -> None: ...
    def update_outlets(self) -> None: ...
    def update_senders(self) -> None: ...
    def update_outputs(self) -> None: ...

class SubmodelsProperty:
    def set_number(self, number: int) -> None: ...
    def put_submodel(
        self, submodel: CyModelProtocol | None, typeid: int, position: int
    ) -> None: ...
    def append_submodel(self, submodel: CyModelProtocol, typeid: int) -> None: ...
