from hydpy.core.typingtools import *

class BaseInterface: ...

class SubmodelsProperty:
    def set_number(self, number: int) -> None: ...
    def put_submodel(
        self, submodel: Optional[CyModelProtocol], typeid: int, position: int
    ) -> None: ...
    def append_submodel(self, submodel: CyModelProtocol, typeid: int) -> None: ...
