# pylint: disable=missing-module-docstring, missing-function-docstring, unused-argument

def smooth_logistic1(value: float, parameter: float) -> float: ...
def smooth_logistic2(value: float, parameter: float) -> float: ...
def smooth_logistic1_derivative2(value: float, parameter: float) -> float: ...
def smooth_logistic2_derivative1(value: float, parameter: float) -> float: ...
def smooth_logistic2_derivative2(value: float, parameter: float) -> float: ...
def smooth_logistic3(value: float, parameter: float) -> float: ...
def smooth_max1(x_value: float, y_value: float, parameter: float) -> float: ...
def smooth_min1(x_value: float, y_value: float, parameter: float) -> float: ...
def smooth_max2(
    x_value: float, y_value: float, z_value: float, parameter: float
) -> float: ...
def smooth_min2(x_value: float, y_value: float, parameter: float) -> float: ...
def filter_norm(value: float, mean: float, std: float) -> float: ...
